# trigger redeploy
import os
import re
import io
import csv
import hashlib
import hmac
import secrets
from collections import Counter
from datetime import date, datetime, timedelta, timezone
from typing import Optional, List

from fastapi import FastAPI, HTTPException, Depends, Header, UploadFile, File, Form
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse, Response
from pydantic import BaseModel
from motor.motor_asyncio import AsyncIOMotorClient, AsyncIOMotorGridFSBucket
from bson import ObjectId
from pymongo.errors import DuplicateKeyError
from jose import jwt, JWTError
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.chart import BarChart, LineChart, Reference
from openpyxl.drawing.image import Image as XLImage
from PIL import Image, UnidentifiedImageError
import certifi
import ssl

from week_dates import (
    DAY_LABELS,
    DAY_OFFSET,
    DAY_ORDER,
    MONTHS,
    activity_date_for_day,
    activity_date_for_day_date,
    current_week_key,
    format_week_label,
    normalise_new_activity_date,
    sast_today,
    validate_campaign_activity_date,
    validate_campaign_date_range,
    validate_candidate_week_key,
    week_key_and_day_for_date,
)
from smartsheet_reporting import (
    CANVASSING,
    DEFAULT_CONSTITUENCY,
    PRESENCE,
    PUBLIC_STREET_MEETING,
    REVIEWABLE_CATEGORIES,
    is_new_other_submission,
    review_entries,
    reporting_metadata_for_submission,
    smartsheet_csv_bytes,
    smartsheet_workbook_all_categories_bytes,
    smartsheet_xlsx_bytes,
    summarize_smartsheet_entries,
    validate_time_range,
    normalise_venue,
)
from activity_validation import location_is_ward_only
import official_capture
import leadership_reporting


# Atlas on this host rejects TLS 1.3 (TLSV1_ALERT_INTERNAL_ERROR); cap at TLS 1.2.
_original_create_default_context = ssl.create_default_context


def _create_default_context_tls12(*args, **kwargs):
    context = _original_create_default_context(*args, **kwargs)
    context.maximum_version = ssl.TLSVersion.TLSv1_2
    return context


ssl.create_default_context = _create_default_context_tls12

# ---------- Config ----------
MONGO_URI = os.environ["MONGO_URI"]                     # required - set in Railway
DB_NAME = os.environ.get("DB_NAME", "ward_tracker")
ADMIN_PIN = os.environ["ADMIN_PIN"]                      # required - your coordinator PIN
JWT_SECRET = os.environ["JWT_SECRET"]                    # required - long random string
JWT_ALGO = "HS256"
JWT_EXPIRE_DAYS = 30
DEFAULT_LEADER_PIN_HASH = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4"  # temporary PIN 1234
LEADER_PIN_HASH = (
    os.environ.get("COORDINATOR_LEADER_PIN_HASH")
    or os.environ.get("LEADER_PIN_HASH")
    or DEFAULT_LEADER_PIN_HASH
)
LEADER_PIN = os.environ.get("COORDINATOR_LEADER_PIN") or os.environ.get("LEADER_PIN")
FRONTEND_ORIGIN = os.environ.get("FRONTEND_ORIGIN", "*")  # set to your Vercel URL once deployed
LOGO_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "static", "logo.png")
CONSTITUENCY = os.environ.get("CONSTITUENCY", DEFAULT_CONSTITUENCY)

app = FastAPI(title="Ntsikana Ward Tracker API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=[FRONTEND_ORIGIN] if FRONTEND_ORIGIN != "*" else ["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

client = AsyncIOMotorClient(MONGO_URI, tlsCAFile=certifi.where())
db = client[DB_NAME]
entries_col = db["entries"]
roster_col = db["roster"]
campaigns_col = db["campaigns"]
evidence_bucket = AsyncIOMotorGridFSBucket(db, bucket_name="evidence_photos")
MAX_EVIDENCE_PHOTO_BYTES = 6 * 1024 * 1024
MAX_EVIDENCE_IMAGE_SIDE = 1800
SUPPORTED_EVIDENCE_FORMATS = {"JPEG": "image/jpeg", "PNG": "image/png", "WEBP": "image/webp"}


@app.on_event("startup")
async def ensure_indexes():
    await entries_col.create_index([("person_id", 1), ("week_key", 1)])
    await roster_col.create_index("name_slug", unique=True)
    # Additive only: existing entries documents have no campaign_id field at
    # all, which Mongo indexes identically to campaign_id: null — no backfill
    # needed for this index to be useful once campaign-linked activities exist.
    await entries_col.create_index("campaign_id")
    await entries_col.create_index([("campaign_id", 1), ("activity_date", 1)])
    await entries_col.create_index("activity_date")
    await entries_col.create_index([("week_key", 1), ("person_id", 1)])
    # Partial: only applies to documents that actually have a recurrence_id
    # (i.e. generated by the repeat-activity endpoint), so every existing and
    # future non-recurring activity is completely untouched by this
    # constraint. Enforces "a retry of the same repeat request can't
    # duplicate an occurrence" at the database level, on top of the
    # application-level pre-check in create_campaign_activity_repeat.
    await entries_col.create_index(
        [("recurrence_id", 1), ("activity_date", 1)],
        unique=True,
        partialFilterExpression={"recurrence_id": {"$exists": True}},
    )
    await campaigns_col.create_index([("person_id", 1), ("start_date", -1)])
    await campaigns_col.create_index([("start_date", 1), ("end_date", 1)])


# ---------- Helpers ----------

# Phase 5.1 (wording updated in the 5.1.1 municipality-label correction): a
# new activity's location must be an actual place, not the candidate's
# roster ward/municipality restated (the coordinator needs a real place to
# transcribe into the official Campaign Manager). Shared by ordinary and
# campaign activity creation so the message/rule never drifts between the
# two paths. The underlying `ward` field/column is unchanged — this is a
# candidate-facing wording choice only ("Municipality" in the UI).
LOCATION_REQUIRED_MESSAGE = "Please enter the specific location or venue within your municipality."


def slugify(s: str) -> str:
    s = s.strip().lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


def oid_str(doc: dict) -> dict:
    doc = dict(doc)
    doc["id"] = str(doc.pop("_id"))
    return doc


def enrich_entry(doc: dict) -> dict:
    doc = dict(doc)
    week_key = doc.get("week_key")
    day = doc.get("day")
    if week_key:
        doc["week_label"] = format_week_label(week_key)
    if week_key and day in DAY_OFFSET and not doc.get("activity_date"):
        doc["activity_date"] = activity_date_for_day(week_key, day)
    # Additive, read-time-only defaults (Phase 4): a historical document with
    # no capture_status/official_activity_type is never rewritten — this
    # dict mutation is never persisted back to Mongo. CandidateEntryOut
    # doesn't declare these fields, so FastAPI's response_model filtering
    # already keeps them out of every candidate-facing response regardless.
    doc["capture_status"] = official_capture.resolve_capture_status(doc)
    doc["official_activity_type"] = official_capture.resolve_official_activity_type(doc)
    return doc


def entry_for_response(doc: dict) -> dict:
    return enrich_entry(oid_str(doc))


async def hydrate_entry_participants(doc: dict) -> dict:
    doc = dict(doc)
    ids = normalize_participant_ids(doc.get("participant_ids"))
    doc["participant_ids"] = ids
    doc["other_participants"] = normalize_other_participants(doc.get("other_participants"))
    doc["evidence_photos"] = normalize_evidence_refs(doc.get("evidence_photos"))
    participants = []
    if ids:
        roster_docs = [oid_str(r) async for r in roster_col.find({"name_slug": {"$in": ids}})]
        by_slug = {r.get("name_slug"): r for r in roster_docs}
        for pid in ids:
            person = by_slug.get(pid)
            if person:
                participants.append({
                    "id": pid,
                    "name": person.get("name") or pid,
                    "ward": person.get("actual_ward") or person.get("ward") or "",
                    "municipality": person.get("municipality") or "",
                })
    doc["roster_participants"] = participants
    return doc


async def entry_for_response_hydrated(doc: dict) -> dict:
    return await hydrate_entry_participants(entry_for_response(doc))


async def validate_evidence_refs_for_person(refs: list[dict], person_id: str) -> None:
    if not refs:
        raise HTTPException(400, "Please add at least one photo before submitting this activity.")
    for ref in refs:
        try:
            oid = ObjectId(ref["id"])
            stream = await evidence_bucket.open_download_stream(oid)
        except Exception:
            raise HTTPException(400, "Photo evidence could not be found. Please upload it again.")
        metadata = getattr(stream, "metadata", {}) or {}
        if metadata.get("owner_person_id") != person_id:
            raise HTTPException(400, "Photo evidence does not match this candidate.")


async def validate_participant_ids(ids: list[str]) -> None:
    if not ids:
        return
    found = {
        doc.get("name_slug")
        async for doc in roster_col.find({"name_slug": {"$in": ids}}, {"name_slug": 1})
    }
    if any(pid not in found for pid in ids):
        raise HTTPException(400, "One or more selected roster participants could not be found.")


def normalize_name_words(name: str) -> set:
    # Strips titles like "(CLLR)" so a name typed without middle names/suffixes
    # still matches its fuller roster form.
    name = re.sub(r"\([^)]*\)", "", name)
    name = re.sub(r"[^a-z0-9\s]", "", name.lower())
    return set(w for w in name.split() if w)


def names_match(a: str, b: str) -> bool:
    words_a, words_b = normalize_name_words(a), normalize_name_words(b)
    if not words_a or not words_b:
        return False
    return words_a <= words_b or words_b <= words_a


async def resolve_and_canonicalize_person(body: "EntryIn") -> None:
    """Validate the submitted candidate against the official roster and replace
    whatever name/ward/person_id the client sent with the roster's canonical
    values. This is the backend enforcement point: it runs for every entry
    create/update regardless of whether the request came through the UI, so a
    direct API call cannot invent a new person or attach itself to the wrong
    roster identity by spelling/case/abbreviation variation."""
    roster_person = await roster_col.find_one({"name_slug": slugify(body.name)})
    if not roster_person:
        raise HTTPException(400, "Please select your name from the roster.")
    body.name = roster_person["name"]
    body.ward = roster_person.get("ward", "")
    body.person_id = roster_person["name_slug"]


async def resolve_campaign_person_id(person_id: str) -> str:
    """Same roster-only identity enforcement as entries: a campaign may only
    belong to an actual roster person. `person_id` here is whatever identity
    string the client is currently using (today's frontend always sends the
    slug of the selected roster person's canonical name, which already
    equals that roster entry's name_slug) — re-slugifying it is a no-op for
    an already-canonical slug and correctly resolves a raw name too. The
    client-sent value is never trusted directly; only the roster's own
    name_slug is stored, exactly as resolve_and_canonicalize_person does for
    entries."""
    roster_person = await roster_col.find_one({"name_slug": slugify(person_id)})
    if not roster_person:
        raise HTTPException(400, "Please select your name from the roster.")
    return roster_person["name_slug"]


def campaign_doc_from_body(body: "CampaignIn") -> dict:
    """Deliberately excludes person_id: ownership is resolved and applied
    separately by each route (set once at create, never accepted from an
    update body afterwards), so a mutable field never sneaks back in here."""
    name = (body.name or "").strip()
    if not name:
        raise HTTPException(400, "Campaign name is required")
    try:
        start, end = validate_campaign_date_range(body.start_date, body.end_date)
    except ValueError as exc:
        raise HTTPException(400, str(exc))
    doc = {
        "name": name,
        "start_date": start.isoformat(),
        "end_date": end.isoformat(),
    }
    doc["purpose"] = (body.purpose or "").strip()
    return doc


def derive_campaign_status(doc: dict, now: Optional[datetime] = None) -> str:
    """Planned/active/completed are pure functions of today vs the stored
    dates and are deliberately NOT persisted, so they can never drift out of
    sync with the calendar. archived_at is the only stored, manual state."""
    if doc.get("archived_at"):
        return "archived"
    today = sast_today(now)
    start = date.fromisoformat(doc["start_date"])
    end = date.fromisoformat(doc["end_date"])
    if today < start:
        return "planned"
    if today > end:
        return "completed"
    return "active"


def campaign_for_response(doc: dict) -> dict:
    doc = oid_str(doc)
    doc["status"] = derive_campaign_status(doc)
    return doc


async def require_campaign_owner(campaign_id: str, person_id: str) -> tuple[dict, str]:
    """Resolve the caller's claimed identity against the roster (rejecting an
    unknown identity exactly like create_campaign does), then load the
    campaign only if it belongs to that resolved identity. A campaign that
    exists but belongs to someone else is deliberately indistinguishable
    from one that doesn't exist (404) — the same convention update_entry/
    delete_entry already use for person-scoped entries, so a wrong guess at
    someone else's campaign_id never confirms it exists or reveals its
    owner. There is no admin bypass here; this is candidate-facing only."""
    owner_person_id = await resolve_campaign_person_id(person_id)
    doc = await campaigns_col.find_one({"_id": ObjectId(campaign_id), "person_id": owner_person_id})
    if not doc:
        raise HTTPException(404, "Campaign not found")
    return doc, owner_person_id


async def require_roster_person(person_id: str) -> dict:
    """Fetch the full roster document for an already-resolved name_slug.
    Used right after require_campaign_owner, which only returns the slug —
    kept as a separate small lookup rather than changing that function's
    signature, so Phase 1's already-verified ownership checks stay untouched."""
    roster_person = await roster_col.find_one({"name_slug": person_id})
    if not roster_person:
        raise HTTPException(400, "Please select your name from the roster.")
    return roster_person


def reject_if_archived(
    campaign: dict, message: str = "Archived campaigns cannot accept new activities."
) -> None:
    """Archiving is the normal terminal action for a campaign — it must
    read as closed. This never deletes or modifies any existing activity;
    reads (GET .../activities) are always untouched. Phase 5 reuses this same
    guard (with a context-appropriate message) to also block editing the
    campaign itself and editing an activity that belongs to it — "archived"
    means frozen from every candidate mutation, not just new activities."""
    if campaign.get("archived_at"):
        raise HTTPException(409, message)


def campaign_activity_base_doc(
    roster_person: dict,
    campaign_id: str,
    activity_date: date,
    type_: str,
    type_display: str,
    notes: Optional[str],
    start_time: Optional[str],
    end_time: Optional[str],
    venue: Optional[str],
) -> dict:
    """Shared field-building for both single and repeat campaign-activity
    creation: derives week_key/day from the absolute date (campaign
    activities are dated directly, not picked via week_key+day), then
    reuses the exact same time/venue/Other/SmartSheet-classification logic
    every other activity goes through, so a campaign activity is
    indistinguishable in shape from a plain one anywhere it's displayed."""
    week_key, day = week_key_and_day_for_date(activity_date)
    doc = {
        "person_id": roster_person["name_slug"],
        "name": roster_person["name"],
        "ward": roster_person.get("ward", ""),
        "campaign_id": campaign_id,
        "day": day,
        "type": type_,
        "type_display": type_display,
        "notes": notes,
        "week_key": week_key,
        "week_label": format_week_label(week_key),
        "activity_date": activity_date.isoformat(),
    }
    try:
        doc["start_time"], doc["end_time"] = validate_time_range(start_time, end_time)
    except ValueError as exc:
        raise HTTPException(400, str(exc))
    doc["venue"] = normalise_venue(venue)
    # Always a creation path (single or repeat campaign activity) — location
    # is required and must not just restate the ward, same rule
    # entry_doc_from_body applies on its create branch.
    if not doc["venue"] or location_is_ward_only(doc["venue"], doc.get("ward")):
        raise HTTPException(400, LOCATION_REQUIRED_MESSAGE)
    if is_new_other_submission(doc):
        other_text = (doc.get("type_display") or "").strip()
        if not other_text:
            raise HTTPException(400, "Other activity text is required")
        doc["type_display"] = other_text
    doc.update(reporting_metadata_for_submission(doc))
    # Always a creation path (single or repeat campaign activity) — explicit
    # per CAMPAIGNS.md §4, same as entry_doc_from_body's create branch.
    doc["capture_status"] = official_capture.AWAITING_CAPTURE
    return doc


def compute_recurrence_id(campaign_id: str, body: "CampaignActivityRepeatIn") -> str:
    """Deterministic id for this repeat request's meaningful content. A
    byte-for-byte identical retry (same campaign/weekday/dates/type/time/
    venue) recomputes the same id, so the (recurrence_id, activity_date)
    check/index catches it as a duplicate. Any real difference — a
    different time, venue, or a separate recurring series — produces a
    different id, so two independently-created activities that merely
    share a type and date are never mistaken for the same occurrence."""
    raw = "|".join([
        campaign_id,
        body.weekday,
        body.first_occurrence_date,
        body.until,
        body.type,
        body.type_display,
        body.start_time or "",
        body.end_time or "",
        (body.venue or "").strip(),
    ])
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()[:24]


def _effective_activity_date(doc: dict) -> Optional[str]:
    """Same activity_date fallback enrich_entry uses for display, applied
    here purely for before/after comparison — never persisted."""
    if doc.get("activity_date"):
        return doc["activity_date"]
    if doc.get("week_key") and doc.get("day") in DAY_OFFSET:
        return activity_date_for_day(doc["week_key"], doc["day"])
    return None


def _apply_post_capture_edit_reset(existing_doc: dict, doc: dict) -> None:
    """Phase 5: a candidate edit to an activity the coordinator has already
    marked Captured may invalidate what was transcribed into the official
    Campaign Manager, so it must reopen for re-capture. Only a MEANINGFUL
    change — date, start/end time, venue, or the Ward Tracker activity type
    itself — does this; a notes-only edit or a PUT that resubmits identical
    values must never disturb an already-captured activity. Mutates `doc`
    in place by adding capture_status/captured_at/official_activity_type
    keys ONLY when a reset is actually warranted — otherwise `doc` gains no
    such keys, exactly like every other (non-captured) edit already worked
    before this phase, leaving update_entry_capture as the only other writer
    of these fields."""
    if official_capture.resolve_capture_status(existing_doc) != official_capture.CAPTURED:
        return
    schedule_or_location_changed = (
        _effective_activity_date(existing_doc) != doc.get("activity_date")
        or existing_doc.get("start_time") != doc.get("start_time")
        or existing_doc.get("end_time") != doc.get("end_time")
        or existing_doc.get("venue") != doc.get("venue")
    )
    type_changed = (
        existing_doc.get("type") != doc.get("type")
        or existing_doc.get("type_display") != doc.get("type_display")
    )
    if not (schedule_or_location_changed or type_changed):
        return
    doc["capture_status"] = official_capture.AWAITING_CAPTURE
    doc["captured_at"] = None
    if type_changed:
        # The source activity itself changed — the coordinator must
        # reconfirm the official type rather than keep a stale override.
        doc["official_activity_type"] = None


def entry_doc_from_body(
    body: "EntryIn", existing_doc: Optional[dict] = None, campaign: Optional[dict] = None
) -> dict:
    """`campaign` is only ever passed by update_entry, and only when the
    entry being edited already has a campaign_id — it's how an existing
    campaign-linked occurrence gets re-validated against its own campaign's
    date range on edit instead of the candidate current/next-week rule.
    Plain entries (campaign=None, the only case for create_entry) are
    completely unaffected — this is a separate branch, not a relaxation of
    validate_candidate_week_key."""
    doc = body.model_dump()
    doc["participant_ids"] = normalize_participant_ids(doc.get("participant_ids"))
    doc["other_participants"] = normalize_other_participants(doc.get("other_participants"))
    doc["evidence_photos"] = normalize_evidence_refs(doc.get("evidence_photos"))
    try:
        if campaign:
            activity_date = validate_campaign_activity_date(
                campaign["start_date"], campaign["end_date"], doc.get("activity_date") or ""
            )
            week_key, day = week_key_and_day_for_date(activity_date)
            doc["week_key"] = week_key
            doc["day"] = day
            doc["week_label"] = format_week_label(week_key)
            doc["activity_date"] = activity_date.isoformat()
        else:
            validate_candidate_week_key(doc["week_key"])
            doc["week_label"] = format_week_label(doc["week_key"])
            doc["activity_date"] = normalise_new_activity_date(
                doc["week_key"], doc["day"], doc.get("activity_date")
            )
        doc["start_time"], doc["end_time"] = validate_time_range(
            doc.get("start_time"), doc.get("end_time")
        )
        doc["venue"] = normalise_venue(doc.get("venue"))
        if existing_doc is None:
            # New activity only — an edit to a historical record (including
            # one with a legacy blank location) is never newly blocked by
            # this rule, matching the frontend's isNewEntry-only check.
            if not doc["venue"] or location_is_ward_only(doc["venue"], doc.get("ward")):
                raise ValueError(LOCATION_REQUIRED_MESSAGE)
            if campaign is None and not doc["evidence_photos"]:
                raise ValueError("Please add at least one photo before submitting this activity.")
        elif existing_doc.get("evidence_photos") and not doc["evidence_photos"]:
            raise ValueError("Activities with photo evidence must keep at least one photo.")
        if is_new_other_submission(doc):
            other_text = (doc.get("type_display") or "").strip()
            if not other_text:
                raise ValueError("Other activity text is required")
            doc["type_display"] = other_text
    except ValueError as exc:
        raise HTTPException(400, str(exc))
    if existing_doc and doc.get("notes") is None and existing_doc.get("notes"):
        doc["notes"] = existing_doc["notes"]
    doc.update(reporting_metadata_for_submission(doc, existing_doc))
    if existing_doc is None:
        # Explicit at creation (CAMPAIGNS.md §4) — not left to enrich_entry's
        # read-time default.
        doc["capture_status"] = official_capture.AWAITING_CAPTURE
    else:
        # An update's $set only ever includes capture_status/captured_at/
        # official_activity_type when a Captured activity was just
        # meaningfully edited (Phase 5) — otherwise none of those keys are
        # added here, so an awaiting/historical activity's capture state is
        # left completely untouched by editing it, exactly as before.
        _apply_post_capture_edit_reset(existing_doc, doc)
    return doc


def normalize_participant_ids(values: Optional[list]) -> list[str]:
    out = []
    seen = set()
    for value in values or []:
        text = str(value or "").strip()
        if text and text not in seen:
            out.append(text)
            seen.add(text)
    return out


def normalize_other_participants(values: Optional[list]) -> list[str]:
    out = []
    seen = set()
    for value in values or []:
        text = re.sub(r"\s+", " ", str(value or "").strip())
        key = text.casefold()
        if text and key not in seen:
            out.append(text)
            seen.add(key)
    return out


def evidence_url(photo_id: str) -> str:
    return f"/api/evidence/photos/{photo_id}"


def normalize_evidence_refs(values: Optional[list]) -> list[dict]:
    out = []
    seen = set()
    for value in values or []:
        ref = value.model_dump() if hasattr(value, "model_dump") else dict(value or {})
        photo_id = str(ref.get("id") or "").strip()
        if not photo_id or photo_id in seen:
            continue
        try:
            ObjectId(photo_id)
        except Exception:
            continue
        seen.add(photo_id)
        out.append({
            "id": photo_id,
            "filename": sanitize_filename(ref.get("filename") or "photo.jpg"),
            "content_type": str(ref.get("content_type") or "image/jpeg"),
            "size": int(ref.get("size") or 0),
            "url": evidence_url(photo_id),
        })
    return out


def sanitize_filename(filename: object) -> str:
    base = os.path.basename(str(filename or "photo.jpg")).strip()
    base = re.sub(r"[^A-Za-z0-9._-]+", "-", base).strip(".-")
    return base or "photo.jpg"


def prepare_evidence_image(raw: bytes, original_filename: str) -> tuple[bytes, str, str, int, tuple[int, int]]:
    if not raw:
        raise HTTPException(400, "Photo file is empty.")
    if len(raw) > MAX_EVIDENCE_PHOTO_BYTES:
        raise HTTPException(400, "Photo is too large. Please choose a smaller image.")
    try:
        img = Image.open(io.BytesIO(raw))
        img.verify()
        img = Image.open(io.BytesIO(raw))
    except (UnidentifiedImageError, OSError):
        raise HTTPException(400, "Please upload a valid image file.")
    fmt = (img.format or "").upper()
    if fmt not in SUPPORTED_EVIDENCE_FORMATS:
        raise HTTPException(400, "Supported photo formats are JPEG, PNG and WEBP.")
    img = Image.open(io.BytesIO(raw))
    img.load()
    if max(img.size) > MAX_EVIDENCE_IMAGE_SIDE:
        img.thumbnail((MAX_EVIDENCE_IMAGE_SIDE, MAX_EVIDENCE_IMAGE_SIDE))
    if fmt == "PNG" and img.mode in {"RGBA", "LA"}:
        out = io.BytesIO()
        img.save(out, format="PNG", optimize=True)
        payload = out.getvalue()
        content_type = "image/png"
        ext = "png"
    else:
        if img.mode not in {"RGB", "L"}:
            img = img.convert("RGB")
        out = io.BytesIO()
        img.save(out, format="JPEG", quality=82, optimize=True)
        payload = out.getvalue()
        content_type = "image/jpeg"
        ext = "jpg"
    safe_name = sanitize_filename(original_filename)
    stem = os.path.splitext(safe_name)[0] or "photo"
    return payload, content_type, f"{stem}.{ext}", len(payload), img.size


def make_role_token(role: str, **extra_claims) -> str:
    payload = {
        "role": role,
        "exp": datetime.now(timezone.utc) + timedelta(days=JWT_EXPIRE_DAYS),
    }
    payload.update(extra_claims)
    return jwt.encode(payload, JWT_SECRET, algorithm=JWT_ALGO)


def make_admin_token() -> str:
    return make_role_token("admin")


def make_leader_token() -> str:
    return make_role_token("coordinator_leader", name="Kevin")


def leader_pin_matches(pin: str) -> bool:
    entered = str(pin or "")
    if LEADER_PIN:
        return hmac.compare_digest(entered, LEADER_PIN)
    expected_hash = str(LEADER_PIN_HASH or "").strip().lower()
    entered_hash = hashlib.sha256(entered.encode("utf-8")).hexdigest()
    return bool(expected_hash) and hmac.compare_digest(entered_hash, expected_hash)


def decode_bearer_token(authorization: Optional[str], missing_message: str) -> dict:
    if not authorization or not authorization.startswith("Bearer "):
        raise HTTPException(401, missing_message)
    token = authorization.split(" ", 1)[1]
    try:
        return jwt.decode(token, JWT_SECRET, algorithms=[JWT_ALGO])
    except JWTError:
        raise HTTPException(401, "Invalid or expired token")


async def require_admin(authorization: Optional[str] = Header(None)):
    payload = decode_bearer_token(authorization, "Missing admin token")
    if payload.get("role") != "admin":
        raise HTTPException(401, "Invalid admin token")
    return True


async def require_leader(authorization: Optional[str] = Header(None)):
    payload = decode_bearer_token(authorization, "Missing leader token")
    if payload.get("role") != "coordinator_leader":
        raise HTTPException(401, "Invalid leader token")
    return True


async def require_admin_or_leader(authorization: Optional[str] = Header(None)):
    payload = decode_bearer_token(authorization, "Missing token")
    if payload.get("role") not in {"admin", "coordinator_leader"}:
        raise HTTPException(401, "Invalid token")
    return True


# ---------- Schemas ----------
class LoginRequest(BaseModel):
    pin: str


class EvidencePhotoRef(BaseModel):
    id: str
    filename: Optional[str] = None
    content_type: Optional[str] = None
    size: Optional[int] = None
    url: Optional[str] = None


class ParticipantRef(BaseModel):
    id: str
    name: str
    ward: Optional[str] = None
    municipality: Optional[str] = None


class EntryIn(BaseModel):
    person_id: str
    name: str
    ward: str
    day: str  # mon..sun
    type: str
    type_display: str
    notes: Optional[str] = None
    week_key: str
    week_label: str
    activity_date: Optional[str] = None
    start_time: Optional[str] = None
    end_time: Optional[str] = None
    venue: Optional[str] = None
    participant_ids: Optional[List[str]] = None
    other_participants: Optional[List[str]] = None
    evidence_photos: Optional[List[EvidencePhotoRef]] = None


class EntryOut(EntryIn):
    id: str
    submitted_at: str
    canonical_activity: Optional[str] = None
    smartsheet_category: Optional[str] = None
    category_source: Optional[str] = None
    category_reviewed: Optional[bool] = None
    category_reviewed_at: Optional[str] = None
    is_custom_activity: Optional[bool] = None
    # Forward-compatible only: no endpoint sets this yet (that's a later
    # campaign-activity-linking phase). Declaring it now on the admin-facing
    # model means that phase won't need a second response-model change.
    # Absent on every existing historical document; defaults to None.
    campaign_id: Optional[str] = None
    # Phase 4 (Official Capture Workspace) — additive only, exactly like
    # campaign_id above. official_activity_type is None until a coordinator
    # explicitly confirms/overrides it; capture_status/captured_at are
    # resolved safely for historical documents by enrich_entry at read time,
    # never backfilled in the database.
    official_activity_type: Optional[str] = None
    capture_status: Optional[str] = None
    captured_at: Optional[str] = None
    roster_participants: Optional[List[ParticipantRef]] = None


# Response shape for the candidate-facing entry endpoints. Deliberately excludes
# SmartSheet/admin-only fields (smartsheet_category, canonical_activity,
# category_source, category_reviewed*) — candidates must never receive that
# terminology, even in a raw network response the UI doesn't render. FastAPI's
# response_model filtering drops any extra fields the handler returns, so this
# is enforced without changing what the handlers themselves compute or store.
class CandidateEntryOut(BaseModel):
    id: str
    day: str
    type: str
    type_display: str
    notes: Optional[str] = None
    week_key: str
    activity_date: Optional[str] = None
    start_time: Optional[str] = None
    end_time: Optional[str] = None
    venue: Optional[str] = None
    participant_ids: Optional[List[str]] = None
    other_participants: Optional[List[str]] = None
    evidence_photos: Optional[List[EvidencePhotoRef]] = None
    roster_participants: Optional[List[ParticipantRef]] = None


class RosterIn(BaseModel):
    name: str
    ward: str
    municipality: Optional[str] = None
    actual_ward: Optional[str] = None


# Admin data-quality correction: changes ONLY the roster's ward/municipality
# text for an existing candidate — never name/name_slug (identity), and
# there is deliberately no way to touch either through this endpoint.
class RosterWardUpdateIn(BaseModel):
    ward: str


class RosterAssignmentUpdateIn(BaseModel):
    municipality: Optional[str] = None
    actual_ward: Optional[str] = None


class ReassignPersonIn(BaseModel):
    name: str  # must be the exact canonical name of an existing roster entry


class CategoryReviewIn(BaseModel):
    smartsheet_category: str


# Official Capture Workspace (Phase 4). Both fields optional so the PATCH can
# confirm/change the official type, change capture status, or both in one
# call — but at least one must be present (enforced in the handler).
class CaptureUpdateIn(BaseModel):
    official_activity_type: Optional[str] = None
    capture_status: Optional[str] = None


# A campaign is deliberately minimal: identity + name + a date range. No
# focus type, area, description, target, budget, photo, or documents — those
# are explicitly out of scope for this phase and should not be added back in
# without a fresh decision, not as an incidental side effect of other work.
class CampaignIn(BaseModel):
    person_id: str
    name: str
    start_date: str
    end_date: str
    purpose: Optional[str] = None


class CampaignOut(BaseModel):
    id: str
    person_id: str
    name: str
    start_date: str
    end_date: str
    purpose: Optional[str] = None
    status: str
    created_at: str
    archived_at: Optional[str] = None


# person_id here is only ever used to prove which roster identity is making
# the request (checked against the campaign's owner) — never trusted for
# name/ward, which are always resolved fresh from the roster. Deliberately
# has no week_key/week_label: campaign activities are dated directly and
# validated against the campaign's own range, not the candidate write window.
class CampaignActivityIn(BaseModel):
    person_id: str
    activity_date: str
    type: str
    type_display: str
    notes: Optional[str] = None
    start_time: Optional[str] = None
    end_time: Optional[str] = None
    venue: Optional[str] = None


class CampaignActivityRepeatIn(BaseModel):
    person_id: str
    weekday: str  # mon..sun
    first_occurrence_date: str  # ISO date; must be within the campaign range and land on `weekday`
    until: str  # ISO date, inclusive; clamped server-side to the campaign's end_date
    type: str
    type_display: str
    notes: Optional[str] = None
    start_time: Optional[str] = None
    end_time: Optional[str] = None
    venue: Optional[str] = None


# ---------- Auth ----------
@app.post("/api/admin/login")
async def admin_login(body: LoginRequest):
    if body.pin != ADMIN_PIN:
        raise HTTPException(401, "Incorrect PIN")
    return {"token": make_admin_token()}


@app.post("/api/leader/login")
async def leader_login(body: LoginRequest):
    if not leader_pin_matches(body.pin):
        raise HTTPException(401, "Incorrect PIN")
    return {"token": make_leader_token(), "user": {"name": "Kevin", "role": "coordinator_leader"}}


# ---------- Evidence photos ----------
@app.post("/api/evidence/photos")
async def upload_evidence_photo(
    person_id: str = Form(...),
    name: str = Form(...),
    file: UploadFile = File(...),
):
    roster_person = await require_roster_person(slugify(person_id))
    if not names_match(name, roster_person.get("name", "")):
        raise HTTPException(400, "Please select your name from the roster.")
    raw = await file.read()
    payload, content_type, filename, size, dimensions = prepare_evidence_image(raw, file.filename or "photo.jpg")
    photo_id = await evidence_bucket.upload_from_stream(
        filename,
        payload,
        metadata={
            "owner_person_id": roster_person["name_slug"],
            "owner_name": roster_person["name"],
            "content_type": content_type,
            "size": size,
            "width": dimensions[0],
            "height": dimensions[1],
            "uploaded_at": datetime.now(timezone.utc).isoformat(),
            "nonce": secrets.token_urlsafe(16),
        },
    )
    return {
        "id": str(photo_id),
        "filename": filename,
        "content_type": content_type,
        "size": size,
        "url": evidence_url(str(photo_id)),
    }


@app.get("/api/evidence/photos/{photo_id}")
async def get_evidence_photo(
    photo_id: str,
    person_id: Optional[str] = None,
    authorization: Optional[str] = Header(None),
):
    try:
        oid = ObjectId(photo_id)
    except Exception:
        raise HTTPException(404, "Photo not found")
    try:
        stream = await evidence_bucket.open_download_stream(oid)
        data = await stream.read()
    except Exception:
        raise HTTPException(404, "Photo not found")
    metadata = getattr(stream, "metadata", {}) or {}
    if authorization:
        await require_admin_or_leader(authorization)
    elif not person_id or str(person_id) != str(metadata.get("owner_person_id") or ""):
        raise HTTPException(401, "Photo access requires permission")
    return Response(content=data, media_type=metadata.get("content_type") or "image/jpeg")


# ---------- Member: entries ----------
@app.get("/api/entries", response_model=List[CandidateEntryOut])
async def list_my_entries(person_id: str, week_key: str):
    cursor = entries_col.find({"person_id": person_id, "week_key": week_key})
    out = []
    async for doc in cursor:
        out.append(await entry_for_response_hydrated(doc))
    return out


@app.post("/api/entries", response_model=CandidateEntryOut)
async def create_entry(body: EntryIn):
    await resolve_and_canonicalize_person(body)
    doc = entry_doc_from_body(body)
    await validate_participant_ids(doc.get("participant_ids") or [])
    await validate_evidence_refs_for_person(doc.get("evidence_photos") or [], body.person_id)
    doc["submitted_at"] = datetime.now(timezone.utc).isoformat()
    res = await entries_col.insert_one(doc)
    doc["_id"] = res.inserted_id
    return await entry_for_response_hydrated(doc)


@app.put("/api/entries/{entry_id}", response_model=CandidateEntryOut)
async def update_entry(entry_id: str, body: EntryIn):
    await resolve_and_canonicalize_person(body)
    existing_doc = await entries_col.find_one({"_id": ObjectId(entry_id), "person_id": body.person_id})
    if not existing_doc:
        raise HTTPException(404, "Entry not found")
    campaign = None
    if existing_doc.get("campaign_id"):
        campaign = await campaigns_col.find_one({"_id": ObjectId(existing_doc["campaign_id"])})
        if campaign:
            # Phase 5: archived means frozen from candidate mutation, not
            # just closed to new activities — an activity already linked to
            # an archived campaign may still be READ everywhere (admin,
            # exports, candidate history) but never edited by the candidate.
            reject_if_archived(campaign, "This campaign is archived and can no longer be edited.")
    doc = entry_doc_from_body(body, existing_doc, campaign=campaign)
    await validate_participant_ids(doc.get("participant_ids") or [])
    if doc.get("evidence_photos"):
        await validate_evidence_refs_for_person(doc.get("evidence_photos") or [], body.person_id)
    doc["submitted_at"] = datetime.now(timezone.utc).isoformat()

    # Phase 5: an individual occurrence in a recurring series can be edited
    # onto a sibling occurrence's date — pre-check for that collision (the
    # common case) and also catch DuplicateKeyError as a race-condition
    # backstop (mirrors create_campaign_activity_repeat's own pre-check +
    # backstop pattern), so this never surfaces as a raw 500 or leaks any
    # Mongo/database detail.
    recurrence_id = existing_doc.get("recurrence_id")
    if recurrence_id and doc.get("activity_date") != existing_doc.get("activity_date"):
        siblings = [
            d async for d in entries_col.find(
                {"recurrence_id": recurrence_id, "activity_date": doc["activity_date"]}
            )
        ]
        if any(str(d["_id"]) != entry_id for d in siblings):
            raise HTTPException(409, "Another activity in this recurring series already uses that date.")

    try:
        result = await entries_col.find_one_and_update(
            {"_id": ObjectId(entry_id), "person_id": body.person_id},
            {"$set": doc},
            return_document=True,
        )
    except DuplicateKeyError:
        raise HTTPException(409, "Another activity in this recurring series already uses that date.")
    if not result:
        raise HTTPException(404, "Entry not found")
    return await entry_for_response_hydrated(result)


@app.delete("/api/entries/{entry_id}")
async def delete_entry(entry_id: str, person_id: str):
    result = await entries_col.delete_one({"_id": ObjectId(entry_id), "person_id": person_id})
    if result.deleted_count == 0:
        raise HTTPException(404, "Entry not found")
    return {"deleted": True}


# ---------- Member: campaigns ----------
# Phase 1: backend foundation only. Campaigns are a thin, additive container
# — they never rewrite or touch entries documents. No endpoint here creates,
# links, or generates activities; that is a separate later phase.
@app.post("/api/campaigns", response_model=CampaignOut)
async def create_campaign(body: CampaignIn):
    person_id = await resolve_campaign_person_id(body.person_id)
    doc = campaign_doc_from_body(body)
    # Phase 5: a brand-new campaign that has already completely ended is
    # certainly a mistake — reject it. A campaign starting in the past but
    # still active today (end_date >= today) is fine. This check is
    # deliberately create-only: editing an existing historical campaign must
    # never be blocked merely because time has since moved past its end date.
    if date.fromisoformat(doc["end_date"]) < sast_today():
        raise HTTPException(400, "This campaign has already ended. Choose an end date today or in the future.")
    doc["person_id"] = person_id
    doc["created_at"] = datetime.now(timezone.utc).isoformat()
    doc["archived_at"] = None
    res = await campaigns_col.insert_one(doc)
    doc["_id"] = res.inserted_id
    return campaign_for_response(doc)


@app.get("/api/campaigns", response_model=List[CampaignOut])
async def list_campaigns(person_id: str):
    cursor = campaigns_col.find({"person_id": person_id})
    return [campaign_for_response(doc) async for doc in cursor]


@app.get("/api/campaigns/{campaign_id}", response_model=CampaignOut)
async def get_campaign(campaign_id: str):
    doc = await campaigns_col.find_one({"_id": ObjectId(campaign_id)})
    if not doc:
        raise HTTPException(404, "Campaign not found")
    return campaign_for_response(doc)


# Ownership (person_id) is immutable after creation. body.person_id here is
# only ever used to prove which roster identity is making the request — it
# is never written as a "new" owner. require_campaign_owner already 404s if
# it resolves to anyone other than the campaign's existing owner, and
# campaign_doc_from_body's returned dict has no person_id key at all, so the
# $set below structurally cannot change ownership even if that check were
# ever weakened by a future edit.
@app.put("/api/campaigns/{campaign_id}", response_model=CampaignOut)
async def update_campaign(campaign_id: str, body: CampaignIn):
    existing, owner_person_id = await require_campaign_owner(campaign_id, body.person_id)
    # Phase 5: archived is the normal terminal action — frozen from every
    # candidate mutation, not just new activities.
    reject_if_archived(existing, "This campaign is archived and can no longer be edited.")
    doc = campaign_doc_from_body(body)
    # Phase 5: never let a new date range silently exclude an activity that
    # already exists inside this campaign — reject cleanly instead. This
    # never deletes, moves, or otherwise touches the activity itself.
    linked_dates = [
        d["activity_date"]
        async for d in entries_col.find({"campaign_id": campaign_id})
        if d.get("activity_date")
    ]
    if linked_dates:
        earliest, latest = min(linked_dates), max(linked_dates)
        if doc["start_date"] > earliest or doc["end_date"] < latest:
            raise HTTPException(
                400,
                "This campaign has activities scheduled outside the new date range. "
                "Adjust the range, or edit/remove those activities first.",
            )
    result = await campaigns_col.find_one_and_update(
        {"_id": ObjectId(campaign_id), "person_id": owner_person_id},
        {"$set": doc},
        return_document=True,
    )
    if not result:
        raise HTTPException(404, "Campaign not found")
    return campaign_for_response(result)


# The normal terminal action. Archiving only ever sets archived_at — it never
# reads, writes, or otherwise touches entries_col, and it must stay that way:
# linked activities remain fully intact, unmodified, and visible everywhere
# they already appear (admin views, exports, candidate history). Scoped to
# the campaign's owner exactly like update_campaign — knowing a campaign_id
# alone is not enough to archive someone else's campaign.
@app.patch("/api/campaigns/{campaign_id}/archive", response_model=CampaignOut)
async def archive_campaign(campaign_id: str, person_id: str):
    _existing, owner_person_id = await require_campaign_owner(campaign_id, person_id)
    result = await campaigns_col.find_one_and_update(
        {"_id": ObjectId(campaign_id), "person_id": owner_person_id},
        {"$set": {"archived_at": datetime.now(timezone.utc).isoformat()}},
        return_document=True,
    )
    if not result:
        raise HTTPException(404, "Campaign not found")
    return campaign_for_response(result)


# Not part of normal candidate UX — a narrow escape hatch for a
# just-created-by-mistake campaign only. Never cascades to entries: any
# campaign with at least one linked activity is rejected with 409, and there
# is deliberately no code path anywhere that deletes or modifies activities
# as a side effect of a campaign being removed. Scoped to the campaign's
# owner exactly like update/archive — ownership is checked (and 404s on
# mismatch) BEFORE the linked-activity check, so a non-owner can't even learn
# whether someone else's campaign has linked activities.
@app.delete("/api/campaigns/{campaign_id}")
async def delete_campaign(campaign_id: str, person_id: str):
    await require_campaign_owner(campaign_id, person_id)
    linked = await entries_col.find_one({"campaign_id": campaign_id})
    if linked:
        raise HTTPException(409, "Cannot delete a campaign with linked activities")
    result = await campaigns_col.delete_one({"_id": ObjectId(campaign_id)})
    if result.deleted_count == 0:
        raise HTTPException(404, "Campaign not found")
    return {"deleted": True}


# ---------- Member: campaign activities ----------
# Phase 2: campaign activities are real, individual entries documents with
# campaign_id set — never schedule metadata. Date validation here is bound
# to the campaign's own start/end dates via validate_campaign_activity_date,
# a path entirely separate from validate_candidate_week_key — the normal
# /api/entries current/next-week rule is never touched by any route below.
@app.post("/api/campaigns/{campaign_id}/activities", response_model=CandidateEntryOut)
async def create_campaign_activity(campaign_id: str, body: CampaignActivityIn):
    campaign, owner_person_id = await require_campaign_owner(campaign_id, body.person_id)
    reject_if_archived(campaign)
    roster_person = await require_roster_person(owner_person_id)
    try:
        activity_date = validate_campaign_activity_date(
            campaign["start_date"], campaign["end_date"], body.activity_date
        )
    except ValueError as exc:
        raise HTTPException(400, str(exc))
    doc = campaign_activity_base_doc(
        roster_person, campaign_id, activity_date,
        body.type, body.type_display, body.notes,
        body.start_time, body.end_time, body.venue,
    )
    doc["submitted_at"] = datetime.now(timezone.utc).isoformat()
    res = await entries_col.insert_one(doc)
    doc["_id"] = res.inserted_id
    return await entry_for_response_hydrated(doc)


@app.post("/api/campaigns/{campaign_id}/activities/repeat")
async def create_campaign_activity_repeat(campaign_id: str, body: CampaignActivityRepeatIn):
    campaign, owner_person_id = await require_campaign_owner(campaign_id, body.person_id)
    reject_if_archived(campaign)
    roster_person = await require_roster_person(owner_person_id)

    if body.weekday not in DAY_OFFSET:
        raise HTTPException(400, "Invalid weekday")
    try:
        first_date = date.fromisoformat(body.first_occurrence_date)
    except (TypeError, ValueError):
        raise HTTPException(400, "first_occurrence_date must be an ISO calendar date")
    if DAY_ORDER[first_date.weekday()] != body.weekday:
        raise HTTPException(400, "first_occurrence_date does not fall on the given weekday")
    try:
        until = date.fromisoformat(body.until)
    except (TypeError, ValueError):
        raise HTTPException(400, "until must be an ISO calendar date")

    try:
        validate_campaign_activity_date(campaign["start_date"], campaign["end_date"], body.first_occurrence_date)
    except ValueError as exc:
        raise HTTPException(400, str(exc))
    if until < first_date:
        raise HTTPException(400, "until must be on or after first_occurrence_date")

    # Clamp to the campaign's own end date — a client-supplied `until`
    # further out never generates occurrences past the campaign's range.
    campaign_end = date.fromisoformat(campaign["end_date"])
    effective_until = min(until, campaign_end)

    recurrence_id = compute_recurrence_id(campaign_id, body)
    created_ids: list[str] = []
    skipped_dates: list[str] = []

    d = first_date
    while d <= effective_until:
        existing = await entries_col.find_one({
            "recurrence_id": recurrence_id,
            "activity_date": d.isoformat(),
        })
        if existing:
            skipped_dates.append(d.isoformat())
        else:
            doc = campaign_activity_base_doc(
                roster_person, campaign_id, d,
                body.type, body.type_display, body.notes,
                body.start_time, body.end_time, body.venue,
            )
            doc["recurrence_id"] = recurrence_id
            doc["submitted_at"] = datetime.now(timezone.utc).isoformat()
            try:
                res = await entries_col.insert_one(doc)
                created_ids.append(str(res.inserted_id))
            except DuplicateKeyError:
                # Race-condition backstop: the partial unique index catches
                # a concurrent identical retry that slipped past the
                # find_one check above.
                skipped_dates.append(d.isoformat())
        d += timedelta(days=7)

    return {
        "recurrence_id": recurrence_id,
        "created": created_ids,
        "skipped_duplicate_dates": skipped_dates,
    }


@app.get("/api/campaigns/{campaign_id}/activities", response_model=List[CandidateEntryOut])
async def list_campaign_activities(campaign_id: str):
    cursor = entries_col.find({"campaign_id": campaign_id})
    out = [await entry_for_response_hydrated(doc) async for doc in cursor]
    out.sort(key=lambda e: (e.get("activity_date") or "", e.get("start_time") or ""))
    return out


# ---------- Coordinator Leader: read-only reporting ----------
async def leadership_dataset() -> tuple[list[dict], list[dict], list[dict]]:
    entries = [entry_for_response(doc) async for doc in entries_col.find({})]
    roster = [oid_str(doc) async for doc in roster_col.find({})]
    campaigns = [campaign_for_response(doc) async for doc in campaigns_col.find({})]
    return entries, roster, campaigns


def leadership_report_filename(period: dict) -> str:
    start = period.get("start_date", "")
    end = period.get("end_date", "")
    preset = re.sub(r"[^a-z0-9-]+", "-", period.get("preset", "report").lower()).strip("-")
    return f"leadership-report-{preset}-{start}-to-{end}.xlsx"


@app.get("/api/leader/dashboard")
async def leader_dashboard(
    preset: str = "this_week",
    date_from: Optional[str] = None,
    date_to: Optional[str] = None,
    ward: Optional[str] = None,
    person_id: Optional[str] = None,
    _: bool = Depends(require_leader),
):
    entries, roster, campaigns = await leadership_dataset()
    try:
        return leadership_reporting.build_dashboard(
            entries,
            roster,
            campaigns,
            preset=preset,
            date_from=date_from,
            date_to=date_to,
            ward=ward,
            person_id=person_id,
        )
    except ValueError as exc:
        raise HTTPException(400, str(exc))


@app.get("/api/leader/ward-detail")
async def leader_ward_detail(
    ward: str,
    preset: str = "this_week",
    date_from: Optional[str] = None,
    date_to: Optional[str] = None,
    person_id: Optional[str] = None,
    _: bool = Depends(require_leader),
):
    if not (ward or "").strip():
        raise HTTPException(400, "Ward is required")
    entries, roster, campaigns = await leadership_dataset()
    try:
        return leadership_reporting.build_ward_detail(
            entries,
            roster,
            campaigns,
            ward=ward,
            preset=preset,
            date_from=date_from,
            date_to=date_to,
            person_id=person_id,
        )
    except ValueError as exc:
        raise HTTPException(400, str(exc))


@app.get("/api/leader/campaigns/{campaign_id}")
async def leader_campaign_detail(campaign_id: str, _: bool = Depends(require_leader)):
    try:
        oid = ObjectId(campaign_id)
    except Exception:
        raise HTTPException(404, "Campaign not found")
    campaign = await campaigns_col.find_one({"_id": oid})
    if not campaign:
        raise HTTPException(404, "Campaign not found")
    entries, roster, _campaigns = await leadership_dataset()
    return leadership_reporting.build_campaign_detail(campaign_for_response(campaign), entries, roster)


@app.get("/api/leader/export.xlsx")
async def leader_export_xlsx(
    preset: str = "this_week",
    date_from: Optional[str] = None,
    date_to: Optional[str] = None,
    ward: Optional[str] = None,
    person_id: Optional[str] = None,
    _: bool = Depends(require_leader),
):
    entries, roster, campaigns = await leadership_dataset()
    try:
        dashboard = leadership_reporting.build_dashboard(
            entries,
            roster,
            campaigns,
            preset=preset,
            date_from=date_from,
            date_to=date_to,
            ward=ward,
            person_id=person_id,
        )
    except ValueError as exc:
        raise HTTPException(400, str(exc))
    xlsx_bytes = leadership_reporting.leadership_workbook_bytes(entries, roster, campaigns, dashboard)
    filename = leadership_report_filename(dashboard["period"])
    return StreamingResponse(
        iter([xlsx_bytes]),
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )


# ---------- Admin: report ----------
@app.get("/api/admin/report")
async def admin_report(week_key: str, _: bool = Depends(require_admin)):
    cursor = entries_col.find({"week_key": week_key})
    entries = [entry_for_response(doc) async for doc in cursor]
    return {"week_key": week_key, "entries": entries}


@app.get("/api/admin/all")
async def admin_all(_: bool = Depends(require_admin)):
    cursor = entries_col.find({})
    entries = [entry_for_response(doc) async for doc in cursor]
    return {"entries": entries}


# Data-quality correction tool: reassigns an existing entry to a different
# roster identity (name + person_id only) without touching anything else
# about the activity. Exists for merging duplicate-person records created
# before roster-only enforcement existed — deliberately narrower than
# update_entry, which canonicalizes ward too and would overwrite historical
# ward text that must be preserved during a merge.
@app.patch("/api/admin/entries/{entry_id}/reassign-person", response_model=EntryOut)
async def admin_reassign_entry_person(
    entry_id: str, body: ReassignPersonIn, _: bool = Depends(require_admin)
):
    roster_person = await roster_col.find_one({"name_slug": slugify(body.name)})
    if not roster_person:
        raise HTTPException(400, "Target name must match an official roster entry")
    result = await entries_col.find_one_and_update(
        {"_id": ObjectId(entry_id)},
        {"$set": {"name": roster_person["name"], "person_id": roster_person["name_slug"]}},
        return_document=True,
    )
    if not result:
        raise HTTPException(404, "Entry not found")
    return entry_for_response(result)


# ---------- Admin: Official Capture Workspace (Phase 4) ----------
# Derives entirely from entries_col + campaigns_col — no duplicated
# reporting database. Never mutates a document except via the single PATCH
# below, and that PATCH only ever writes official_activity_type/
# capture_status/captured_at — nothing else about the activity.
async def _campaign_name_by_id() -> dict:
    names: dict = {}
    async for c in campaigns_col.find({}):
        names[str(c["_id"])] = c.get("name", "")
    return names


async def _all_capture_rows() -> list[dict]:
    campaign_names = await _campaign_name_by_id()
    rows = []
    async for doc in entries_col.find({}):
        row = entry_for_response(doc)
        campaign_name = campaign_names.get(row.get("campaign_id"))
        rows.append(official_capture.augment_entry(row, campaign_name))
    return rows


@app.get("/api/admin/official-capture")
async def admin_official_capture(_: bool = Depends(require_admin)):
    all_rows = await _all_capture_rows()
    counts = official_capture.compute_counts(all_rows)
    ordered = official_capture.sort_oldest_first(all_rows)
    return {
        "counts": counts,
        "entries": ordered,
        "official_activity_types": official_capture.OFFICIAL_ACTIVITY_TYPES,
    }


@app.get("/api/admin/official-capture/export.xlsx")
async def admin_official_capture_export_xlsx(
    status: Optional[str] = None,
    person_id: Optional[str] = None,
    campaign_id: Optional[str] = None,
    official_activity_type: Optional[str] = None,
    date_from: Optional[str] = None,
    date_to: Optional[str] = None,
    _: bool = Depends(require_admin),
):
    all_rows = await _all_capture_rows()
    filtered = official_capture.filter_entries(
        all_rows,
        status=status,
        person_id=person_id,
        campaign_id=campaign_id,
        official_activity_type=official_activity_type,
        date_from=date_from,
        date_to=date_to,
    )
    ordered = official_capture.sort_oldest_first(filtered)
    xlsx_bytes = official_capture.official_capture_xlsx_bytes(ordered)
    return StreamingResponse(
        iter([xlsx_bytes]),
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": "attachment; filename=official-capture-export.xlsx"},
    )


@app.patch("/api/admin/entries/{entry_id}/capture")
async def update_entry_capture(
    entry_id: str, body: CaptureUpdateIn, _: bool = Depends(require_admin)
):
    if body.official_activity_type is None and body.capture_status is None:
        raise HTTPException(400, "Nothing to update")

    existing = await entries_col.find_one({"_id": ObjectId(entry_id)})
    if not existing:
        raise HTTPException(404, "Entry not found")

    updates: dict = {}
    if body.official_activity_type is not None:
        try:
            updates["official_activity_type"] = official_capture.validate_official_activity_type(
                body.official_activity_type
            )
        except ValueError as exc:
            raise HTTPException(400, str(exc))
    if body.capture_status is not None:
        try:
            status = official_capture.validate_capture_status(body.capture_status)
        except ValueError as exc:
            raise HTTPException(400, str(exc))
        if status == official_capture.CAPTURED:
            # Phase 5: never let an activity disappear from the Awaiting
            # Capture queue with its official type still unresolved — this
            # accepts either a confident automatic suggestion or a
            # confirmed override (whichever this same request just applied,
            # or one already stored), never requiring the suggestion to be
            # persisted merely to qualify.
            effective = dict(existing)
            effective.update(updates)
            if not official_capture.resolve_official_activity_type(effective):
                raise HTTPException(400, "Select the official activity type first.")
        updates["capture_status"] = status
        # Server-generated timestamp only — never trust a client-supplied
        # captured_at. Undo always clears it back to null so a re-capture
        # never shows a stale time.
        updates["captured_at"] = (
            datetime.now(timezone.utc).isoformat() if status == official_capture.CAPTURED else None
        )

    result = await entries_col.find_one_and_update(
        {"_id": ObjectId(entry_id)},
        {"$set": updates},
        return_document=True,
    )
    if not result:
        raise HTTPException(404, "Entry not found")

    row = entry_for_response(result)
    campaign_names = await _campaign_name_by_id()
    campaign_name = campaign_names.get(row.get("campaign_id"))
    return official_capture.augment_entry(row, campaign_name)


@app.get("/api/admin/smartsheet/summary")
async def admin_smartsheet_summary(week_key: str, _: bool = Depends(require_admin)):
    cursor = entries_col.find({})
    entries = [entry_for_response(doc) async for doc in cursor]
    return summarize_smartsheet_entries(entries, week_key)


@app.get("/api/admin/smartsheet/review")
async def admin_smartsheet_review(_: bool = Depends(require_admin)):
    cursor = entries_col.find({})
    entries = [entry_for_response(doc) async for doc in cursor]
    return {"entries": review_entries(entries)}


@app.patch("/api/admin/entries/{entry_id}/smartsheet-category", response_model=EntryOut)
async def review_smartsheet_category(
    entry_id: str, body: CategoryReviewIn, _: bool = Depends(require_admin)
):
    category = body.smartsheet_category.strip().upper()
    if category not in REVIEWABLE_CATEGORIES:
        raise HTTPException(400, "Invalid SmartSheet category")
    result = await entries_col.find_one_and_update(
        {"_id": ObjectId(entry_id)},
        {"$set": {
            "smartsheet_category": category,
            "category_source": "admin_review",
            "category_reviewed": True,
            "category_reviewed_at": datetime.now(timezone.utc).isoformat(),
        }},
        return_document=True,
    )
    if not result:
        raise HTTPException(404, "Entry not found")
    return entry_for_response(result)


@app.get("/api/admin/smartsheet/export.csv")
async def admin_smartsheet_export_csv(
    week_key: str,
    category: str,
    _: bool = Depends(require_admin),
):
    normalized_category = category.strip().upper()
    allowed = set(REVIEWABLE_CATEGORIES) | {"ALL"}
    if normalized_category not in allowed:
        raise HTTPException(400, "Invalid SmartSheet export category")
    cursor = entries_col.find({"week_key": week_key})
    entries = [entry_for_response(doc) async for doc in cursor]
    csv_bytes = smartsheet_csv_bytes(entries, week_key, normalized_category, CONSTITUENCY)
    filename_category = {
        CANVASSING: "canvassing",
        PUBLIC_STREET_MEETING: "public-street-meetings",
        PRESENCE: "presence",
        "ALL": "all",
    }[normalized_category]
    return StreamingResponse(
        iter([csv_bytes]),
        media_type="text/csv",
        headers={"Content-Disposition": f"attachment; filename=smartsheet-{filename_category}-{week_key}.csv"},
    )


@app.get("/api/admin/smartsheet/export.xlsx")
async def admin_smartsheet_export_xlsx(
    week_key: str,
    category: str,
    _: bool = Depends(require_admin),
):
    normalized_category = category.strip().upper()
    cursor = entries_col.find({"week_key": week_key})
    entries = [entry_for_response(doc) async for doc in cursor]

    if normalized_category == "ALL":
        # "Download All Excel": one workbook, exactly the three category
        # worksheets — not the flat CSV "ALL" audit dump (that stays CSV-only).
        xlsx_bytes = smartsheet_workbook_all_categories_bytes(entries, week_key, CONSTITUENCY)
        filename = f"ntsikana-smartsheet-all-{week_key}.xlsx"
    elif normalized_category in REVIEWABLE_CATEGORIES:
        xlsx_bytes = smartsheet_xlsx_bytes(entries, week_key, normalized_category, CONSTITUENCY)
        filename_category = {
            CANVASSING: "canvassing",
            PUBLIC_STREET_MEETING: "public-street",
            PRESENCE: "presence",
        }[normalized_category]
        filename = f"ntsikana-smartsheet-{filename_category}-{week_key}.xlsx"
    else:
        raise HTTPException(400, "Invalid SmartSheet export category")

    return StreamingResponse(
        iter([xlsx_bytes]),
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )


@app.get("/api/admin/export.csv")
async def admin_export_csv(_: bool = Depends(require_admin)):
    cursor = entries_col.find({})
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["name", "ward", "week_label", "day", "activity_date", "type", "notes", "submitted_at"])
    async for doc in cursor:
        doc = enrich_entry(doc)
        writer.writerow([
            doc.get("name", ""), doc.get("ward", ""), doc.get("week_label", ""),
            doc.get("day", ""), doc.get("activity_date", ""), doc.get("type_display", doc.get("type", "")),
            doc.get("notes", "") or "", doc.get("submitted_at", ""),
        ])
    csv_bytes = buf.getvalue().encode("utf-8-sig")
    return StreamingResponse(
        iter([csv_bytes]),
        media_type="text/csv",
        headers={"Content-Disposition": "attachment; filename=ward-tracker-export.csv"},
    )


@app.get("/api/admin/export.xlsx")
async def admin_export_xlsx(week_key: Optional[str] = None, _: bool = Depends(require_admin)):
    this_week_key = week_key or current_week_key()
    cursor = entries_col.find({"week_key": this_week_key})

    candidates = {}
    total_activities = 0
    type_counts = Counter()
    day_counts = {d: 0 for d in DAY_ORDER}
    async for doc in cursor:
        doc = enrich_entry(doc)
        total_activities += 1
        name = doc.get("name", "")
        day = doc.get("day", "")
        type_display = doc.get("type_display") or doc.get("type", "")
        notes = (doc.get("notes") or "").strip()

        if type_display:
            type_counts[type_display] += 1
        if day in day_counts:
            day_counts[day] += 1

        c = candidates.setdefault(name, {"ward": doc.get("ward", ""), "days": {}, "notes": {}})
        if not c["ward"]:
            c["ward"] = doc.get("ward", "")
        c["days"][day] = f'{c["days"][day]}, {type_display}' if day in c["days"] else type_display
        if notes:
            c["notes"][day] = f'{c["notes"][day]}; {notes}' if day in c["notes"] else notes

    total_candidates = len(candidates)
    names_sorted = sorted(candidates.keys(), key=lambda n: n.lower())
    roster_docs = [doc async for doc in roster_col.find({})]
    roster_size = len(roster_docs)
    breakdown_str = " | ".join(f"{t}: {n}" for t, n in sorted(type_counts.items()))

    day_dates = {d: activity_date_for_day_date(this_week_key, d) for d in DAY_ORDER}

    headers = (
        ["Name", "Ward"]
        + [f"{DAY_LABELS[d]}\n{day_dates[d].day} {MONTHS[day_dates[d].month - 1]}" for d in DAY_ORDER]
        + ["Notes"]
    )
    n_cols = len(headers)

    wb = Workbook()
    ws = wb.active
    ws.title = "Report"

    if os.path.exists(LOGO_PATH):
        logo_img = XLImage(LOGO_PATH)
        logo_img.width = 50
        logo_img.height = 61
        ws.add_image(logo_img, "A1")
        ws.row_dimensions[1].height = 48

    row = 2
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=n_cols)
    title_cell = ws.cell(row=row, column=1, value="Ntsikana Constituency - Weekly Ward Activity Report")
    title_cell.font = Font(bold=True, size=14, color="153B63")
    row += 1

    summary_top_row = row
    ws.cell(row=row, column=1, value=f"Week: {format_week_label(this_week_key)}"); row += 1
    ws.cell(row=row, column=1, value=f"Generated: {datetime.now(timezone.utc).strftime('%d %b %Y')}"); row += 1
    ws.cell(row=row, column=1, value=f"Total activities this week: {total_activities}"); row += 1
    ws.cell(row=row, column=1, value=f"Total candidates this week: {total_candidates}"); row += 1
    if breakdown_str:
        ws.cell(row=row, column=1, value=f"Activity breakdown: {breakdown_str}"); row += 1
    if roster_size > 0:
        ws.cell(row=row, column=1, value=f"Submission status: {total_candidates} of {roster_size} candidates submitted"); row += 1

    chart_col = n_cols + 2
    ws.cell(row=1, column=chart_col, value="Day")
    ws.cell(row=1, column=chart_col + 1, value="Count")
    for i, d in enumerate(DAY_ORDER):
        ws.cell(row=2 + i, column=chart_col, value=DAY_LABELS[d])
        ws.cell(row=2 + i, column=chart_col + 1, value=day_counts[d])
    ws.column_dimensions[get_column_letter(chart_col)].hidden = True
    ws.column_dimensions[get_column_letter(chart_col + 1)].hidden = True

    chart = BarChart()
    chart.type = "col"
    chart.title = "Activities per day"
    chart.y_axis.title = "Count"
    chart.x_axis.title = "Day"
    chart.legend = None
    chart.width = 8
    chart.height = 6
    chart_data = Reference(ws, min_col=chart_col + 1, min_row=1, max_row=1 + len(DAY_ORDER))
    chart_cats = Reference(ws, min_col=chart_col, min_row=2, max_row=1 + len(DAY_ORDER))
    chart.add_data(chart_data, titles_from_data=True)
    chart.set_categories(chart_cats)
    ws.add_chart(chart, f"{get_column_letter(chart_col)}{summary_top_row}")

    row += 1
    header_row_idx = row
    header_fill = PatternFill(start_color="2568AE", end_color="2568AE", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF")
    thin_side = Side(style="thin", color="DCD6C9")
    thin_border = Border(left=thin_side, right=thin_side, top=thin_side, bottom=thin_side)
    shade_fill = PatternFill(start_color="F3F1EC", end_color="F3F1EC", fill_type="solid")

    for col_idx, header in enumerate(headers, start=1):
        cell = ws.cell(row=header_row_idx, column=col_idx, value=header)
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = thin_border
    ws.row_dimensions[header_row_idx].height = 30

    for row_offset, name in enumerate(names_sorted):
        r_idx = header_row_idx + 1 + row_offset
        c = candidates[name]
        row_fill = shade_fill if row_offset % 2 == 1 else None

        name_cell = ws.cell(row=r_idx, column=1, value=name)
        ward_cell = ws.cell(row=r_idx, column=2, value=c["ward"])
        for cell in (name_cell, ward_cell):
            cell.border = thin_border
            if row_fill:
                cell.fill = row_fill

        for day_idx, day in enumerate(DAY_ORDER):
            col = 3 + day_idx
            value = c["days"].get(day, "")
            cell = ws.cell(row=r_idx, column=col, value=value)
            cell.border = thin_border
            if row_fill:
                cell.fill = row_fill
            if value:
                cell.font = Font(bold=True)

        notes_parts = [f"{DAY_LABELS[d]}: {c['notes'][d]}" for d in DAY_ORDER if d in c["notes"]]
        notes_cell = ws.cell(row=r_idx, column=n_cols, value="; ".join(notes_parts))
        notes_cell.border = thin_border
        if row_fill:
            notes_cell.fill = row_fill

    last_row = header_row_idx + len(names_sorted)
    ws.freeze_panes = f"A{header_row_idx + 1}"

    for col_idx in range(1, n_cols + 1):
        col_letter = get_column_letter(col_idx)
        max_len = max(len(part) for part in headers[col_idx - 1].split("\n"))
        for r_idx in range(header_row_idx + 1, last_row + 1):
            val = ws.cell(row=r_idx, column=col_idx).value
            if val:
                max_len = max(max_len, len(str(val)))
        ws.column_dimensions[col_letter].width = max_len + 2

    not_submitted = sorted(
        (r for r in roster_docs if not any(names_match(n, r.get("name", "")) for n in names_sorted)),
        key=lambda r: r.get("name", "").lower(),
    )
    if not_submitted:
        row = last_row + 2
        ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=n_cols)
        section_title = ws.cell(row=row, column=1, value=f"Not Yet Submitted ({len(not_submitted)} of {roster_size})")
        section_title.font = Font(bold=True, size=12, color="B0473A")
        row += 1
        red_fill = PatternFill(start_color="FDF0EE", end_color="FDF0EE", fill_type="solid")
        for r in not_submitted:
            name_cell = ws.cell(row=row, column=1, value=r.get("name", ""))
            ward_cell = ws.cell(row=row, column=2, value=r.get("ward", ""))
            for cell in (name_cell, ward_cell):
                cell.fill = red_fill
                cell.border = thin_border
            row += 1

    await add_weekly_overview_sheet(wb, this_week_key)

    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return StreamingResponse(
        iter([buf.getvalue()]),
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": "attachment; filename=ward-tracker-report.xlsx"},
    )


async def add_weekly_overview_sheet(wb: Workbook, up_to_week_key: str) -> None:
    """Phase 5.1: an additive "Weekly Overview" sheet on the general admin
    workbook only — never touches the "Report" sheet built above, and has
    nothing to do with the separate SmartSheet workbook/export
    (smartsheet_reporting.py), which this never imports from or writes to.

    Counts ALL activities (campaign-linked and ordinary — campaigns
    themselves live in campaigns_col and are never counted here) grouped by
    the existing Monday-anchored `week_key`, for every week up to and
    including the report's own week — the same "as of this week" boundary
    admin_export_xlsx already applies via `this_week_key`, so a report for
    an earlier week never leaks in activity from weeks after it.

    Fetches all entries (like admin_export_csv/admin_all already do) rather
    than filtering server-side, so this only ever needs the same simple
    equality-based collection queries the rest of this file uses.
    """
    weekly_counts: dict[str, int] = {}
    async for doc in entries_col.find({}, {"week_key": 1}):
        wk = doc.get("week_key")
        if wk and wk <= up_to_week_key:
            weekly_counts[wk] = weekly_counts.get(wk, 0) + 1

    ws = wb.create_sheet("Weekly Overview")
    header_fill = PatternFill(start_color="2568AE", end_color="2568AE", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF")
    thin_side = Side(style="thin", color="DCD6C9")
    thin_border = Border(left=thin_side, right=thin_side, top=thin_side, bottom=thin_side)

    headers = ["Week", "Activities", "Change vs Previous Week"]
    for col_idx, header in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_idx, value=header)
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center")
        cell.border = thin_border

    weeks_sorted = sorted(weekly_counts.keys())
    prev_count = None
    for row_offset, wk in enumerate(weeks_sorted):
        r = 2 + row_offset
        count = weekly_counts[wk]
        week_cell = ws.cell(row=r, column=1, value=format_week_label(wk))
        count_cell = ws.cell(row=r, column=2, value=count)
        change_cell = ws.cell(row=r, column=3)
        if prev_count is None:
            change_cell.value = "-"
        else:
            change_cell.value = count - prev_count
            # A real numeric cell with a signed display format — never a
            # string starting with "+" — so this can never be mistaken for
            # (or misrendered as) a spreadsheet formula.
            change_cell.number_format = "+0;-0;0"
        for cell in (week_cell, count_cell, change_cell):
            cell.border = thin_border
        prev_count = count

    ws.column_dimensions["A"].width = 22
    ws.column_dimensions["B"].width = 12
    ws.column_dimensions["C"].width = 24
    ws.freeze_panes = "A2"

    if weeks_sorted:
        chart = LineChart()
        chart.title = "Weekly Activity Trend"
        chart.y_axis.title = "Activities"
        chart.x_axis.title = "Week"
        chart.width = 20
        chart.height = 10
        last_row = 1 + len(weeks_sorted)
        data_ref = Reference(ws, min_col=2, min_row=1, max_row=last_row)
        cats_ref = Reference(ws, min_col=1, min_row=2, max_row=last_row)
        chart.add_data(data_ref, titles_from_data=True)
        chart.set_categories(cats_ref)
        for series in chart.series:
            series.smooth = False
            series.marker.symbol = "circle"
        ws.add_chart(chart, "E1")


# ---------- Public: roster names (for name autocomplete) ----------
@app.get("/api/roster/names")
async def roster_names():
    cursor = roster_col.find({}, {"_id": 0, "name": 1, "name_slug": 1, "ward": 1, "municipality": 1, "actual_ward": 1})
    return [doc async for doc in cursor]


# ---------- Admin: roster ----------
@app.get("/api/admin/roster")
async def get_roster(_: bool = Depends(require_admin)):
    cursor = roster_col.find({})
    return [oid_str(doc) async for doc in cursor]


@app.get("/api/admin/ward-assignments")
async def get_ward_assignments(_: bool = Depends(require_admin)):
    entries, roster, _campaigns = await leadership_dataset()
    rows = leadership_reporting.assignment_rows(roster, entries)
    return {
        "candidates": rows,
        "missing": sum(1 for row in rows if not row["confirmed_actual_ward"]),
    }


@app.post("/api/admin/roster")
async def add_roster(body: RosterIn, _: bool = Depends(require_admin)):
    doc = body.model_dump()
    doc["name_slug"] = slugify(body.name)
    doc["municipality"] = (body.municipality or "").strip()
    try:
        doc["actual_ward"] = leadership_reporting.normalize_actual_ward_value(body.actual_ward)
    except ValueError as exc:
        raise HTTPException(400, str(exc))
    try:
        res = await roster_col.insert_one(doc)
    except Exception:
        raise HTTPException(409, "That candidate is already on the list")
    doc["_id"] = res.inserted_id
    return oid_str(doc)


@app.patch("/api/admin/roster/{roster_id}")
async def update_roster_ward(roster_id: str, body: RosterWardUpdateIn, _: bool = Depends(require_admin)):
    """Data-quality correction tool (mirrors reassign-person's scope
    discipline): updates only the roster's stored ward/municipality text for
    one existing candidate, in place — never their name, name_slug, or _id,
    so this can never create a duplicate identity. Every activity already
    stores its own `ward` copy at submission time (resolve_and_canonicalize_
    person / campaign_activity_base_doc), so this never touches historical
    activities — only activities submitted after this change pick up the
    new value."""
    result = await roster_col.find_one_and_update(
        {"_id": ObjectId(roster_id)},
        {"$set": {"ward": body.ward}},
        return_document=True,
    )
    if not result:
        raise HTTPException(404, "Not found")
    return oid_str(result)


@app.patch("/api/admin/roster/{roster_id}/assignment")
async def update_roster_assignment(roster_id: str, body: RosterAssignmentUpdateIn, _: bool = Depends(require_admin)):
    try:
        actual_ward = leadership_reporting.normalize_actual_ward_value(body.actual_ward)
    except ValueError as exc:
        raise HTTPException(400, str(exc))
    updates = {
        "municipality": (body.municipality or "").strip(),
        "actual_ward": actual_ward,
    }
    result = await roster_col.find_one_and_update(
        {"_id": ObjectId(roster_id)},
        {"$set": updates},
        return_document=True,
    )
    if not result:
        raise HTTPException(404, "Not found")
    return oid_str(result)


@app.delete("/api/admin/roster/{roster_id}")
async def delete_roster(roster_id: str, _: bool = Depends(require_admin)):
    result = await roster_col.delete_one({"_id": ObjectId(roster_id)})
    if result.deleted_count == 0:
        raise HTTPException(404, "Not found")
    return {"deleted": True}


@app.get("/api/health")
async def health():
    return {"ok": True}
